name: "Publish Neuron Site"
on:
  push:
    branches:
      - master  # or your main branch name
jobs:
  neuron:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build neuron site 🔧
      run: |
        mkdir -p .neuron/output && touch .neuron/output/.nojekyll
        NEURON_FILE=$(ls eolas/neuron/*.md | head -n 1)
        docker run -v $PWD:/notes sridca/neuron neuron gen --pretty-urls /notes/$NEURON_FILE
    - name: Deploy to gh-pages 🚀
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: .neuron/output/
